(() => {
  "use strict";

  const CASES = {
    "zh-Hant": {
      pageTitle: "AlphaCamp｜把學生關係轉成可設計的服務機會",
      eyebrow: "案例研究 · 使用者研究 · 服務設計 · 2021",
      hero: {
        title: "從課後互動不足，\n找出學生關係的五個改善切入點",
        deck: "AlphaCamp 發現學生完成課程後，與平台及學習社群的互動逐漸減少。研究團隊透過學生訪談、關係研究與參與式工作坊，把影響信任、學習支持與社群參與的因素，轉成不同學習情境的服務改善方向。",
        meta: [["角色","使用者研究員｜研究團隊成員"],["團隊","Timothy、Ricky、Kim、Evy"],["期間","2020.11–2021.01"],["範圍","研究與工作坊規劃、訪談、人物誌、關係分析、服務發想"],["證據狀態","研究與服務構想；未宣稱上線成效"]],
        visualCaption: "研究情境概念圖", visualAlt: "程式教育學習歷程、社群支持與職涯方向的概念封面"
      },
      summary: [["問題","課後互動、社群參與與主動分享不足"],["研究","9 位學生訪談＋關係研究"],["收斂","5 個關係改善切入點"],["發想","Kelly 8 個／Tom 9 個方向"]],
      toc: [["01","商業問題","problem"],["02","研究洞察","research"],["03","研究收斂","synthesis"],["04","服務發想","ideation"],["05","產出與狀態","outcome"]],
      overview: {
        label:"案例摘要", title:"把「學生與平台的關係」拆成具體可研究的問題",
        body:"團隊從課後互動不足出發，辨識影響關係的因素、建立三種人物誌、歸納五個改善切入點，再把研究結果轉成不同學習情境的服務構想。",
        contributionLabel:"我的貢獻", contributionIntro:"我是四人研究團隊成員之一。以下分開標示我主責與共同執行的工作，團隊研究產出不等同於個人單獨完成。",
        contributions:[["主責","研究規劃","規劃研究框架、研究流程，以及內部與參與式工作坊的進行方式。"],["共同執行","訪談與歸納","參與學生、助教與專家訪談，整理紀錄並歸納人物誌與關係因素。"],["主責主持","服務發想工作坊","帶領團隊針對 Kelly 與 Tom 展開服務方向，並依急迫性與發生頻率整理情境。"],["設計轉譯","流程與服務草圖","把學習需求整理成服務流程與概念草圖，例如技能樹與提問介面。"]]
      },
      problem:{marker:"商業問題與研究目標",title:"學生完成課程後，為什麼很少繼續與平台互動？",body:["AlphaCamp 觀察到三個現象：課程結束後互動逐漸減少、學習社群參與不如預期，學生也較少主動分享學習成果。團隊知道關係沒有延續，卻還不清楚問題發生在哪些學習環節。","研究因此不直接尋找新功能，而是回到完整學習歷程，理解學生如何建立信任、哪些經驗會促進或破壞關係，以及什麼條件會讓他們更願意持續參與和分享。"],note:"這裡的「關係」指學生與 AlphaCamp 在課程及課後的持續互動、信任、學習支持、社群參與與主動分享意願，不只是抽象的品牌好感。",cards:[["01","利益關係人","整理學生、助教、專家與平台之間的互動網絡。"],["02","課程旅程","定位可能影響關係的學習階段與接觸點。"],["03","早期假設","把人物誌假設轉成待訪談檢查的研究問題。"]]},
      research:{marker:"使用者研究與關係洞察",title:"不同學生面臨不同阻力，影響關係的因素也不一樣",body:"團隊實際訪談 9 位正在學習程式的學生，包含 4 位 AlphaCamp 學員與 5 位非 AlphaCamp 學員，並整理助教與專家觀點。訪談涵蓋學習動機、能力焦慮、助教影響、情緒支持、社群價值與品牌定位。",personas:[["KELLY","轉職者","想確認能力與業界需求的差距，也需要在不確定與挫折中得到方向和鼓勵。","persona-kelly-mosaic.png"],["TOM","在職進修者","需要兼顧工作與學習，重視內容品質、時間效率、課程彈性與持續習慣。","persona-tom-mosaic.png"],["AMY","探索者","重視同儕交流與共同學習；獨自學習和找不到程度相近的夥伴會影響參與。","persona-amy-mosaic.png"]],spectrumLabel:"關係光譜",spectrumTitle:"關係不是有或沒有，而是從交易逐步走向理解與支持",spectrum:[["01","單向交易","付費取得內容或服務，互動以功能交換為主。"],["02","互利夥伴","彼此提供價值，開始形成持續合作。"],["03","雙向交流","願意分享經驗，也期待被理解與回應。"],["04","深入支持","理解個人目標，在困難與成長中提供支持。"]],letterLabel:"研究方法｜情書與分手信",letterTitle:"請學生描述什麼讓關係加深，又是什麼讓他們想離開",letterIntro:"團隊將參與者的內容整理成兩組關係訊號。下圖是依研究內容重新製作的匿名視覺摘要，不是原始手寫資料。",letterAlt:"情書與分手信研究內容的匿名視覺摘要",letterGroups:[["情書","安全感、引導與成長支持","有人及時回應問題、協助理解進度，並把學習內容與個人目標連結起來。"],["分手信","壓力、孤單與聯繫中斷","課程負荷難以維持、缺少即時互動，也不清楚自己的學習狀態與下一步。"]],letterCaption:"研究內容經匿名化與視覺重製；未保留參與者姓名、照片、筆跡或原句。",note:"孤立感是其中一項關係阻力，不是這份研究已驗證的單一流失原因。"},
      synthesis:{marker:"研究收斂",title:"把抽象的學生關係，轉成五個可以改善的方向",body:"團隊把分散的關係因素整理成五個改善切入點，讓後續工作坊能從共同問題出發。它們是機會領域，不是五項已上線服務。",cards:[["01","品牌第一印象","釐清內容價值、服務方式與平台定位。"],["02","助教品質","提高回應品質、深度與信任。"],["03","社群互動","讓學生感受到真實交流與同儕支持。"],["04","個人成長","看見進度、能力差距與下一步。"],["05","業界心態","連結實務需求、職涯與產業資源。"]]},
      ideation:{marker:"服務發想與情境整合",title:"從五個改善方向，發展成不同學習情境的服務構想",body:"團隊先針對不同學習需求展開服務發想：Kelly 形成 8 個方向，Tom 形成 9 個方向，再依情境的急迫性與發生頻率排列，找出優先討論的題目。這些是工作坊中的發想空間，不代表 17 項正式排入開發或已上線的功能。",directions:[["Kelly｜8 個方向","學習診療室、學習路徑圖、你問我答、練功房、Side Project、職涯透視、啦啦隊、大休息。"],["Tom｜9 個方向","碎片化小步學習、魔鬼藏在習慣裡、你問我答、新手村、學習指南針、個人化學習、資訊圖書館、業界情報站、你我共學。"]],proof:[["研究輸入","學生阻力與關係因素","從訪談理解學習焦慮、時間限制、支持需求與職涯期待。"],["收斂方式","五個改善切入點","把分散洞察整理成團隊能共同發想的問題空間。"],["服務輸出","Kelly 8／Tom 9 個方向","依不同學習情境展開服務構想，而非直接定義功能清單。"]],scenarios:[["代表情境 A","作業卡關與不敢提問","研究阻力","不會描述問題、找不到人問、不好意思公開發問，或無法判斷網路內容是否正確。","服務構想","問題描述練習、匿名提問、同程度分組，以及助教或教練協助。",["不知道怎麼描述問題","害怕公開提問","難以判斷答案是否可信"],["問題描述練習","匿名提問與同程度分組","助教／教練與可信答案"]],["代表情境 B","不知道自己學到了什麼","研究阻力","學生仍不確定自己的能力、進度，以及離目標職位還有多少差距。","服務構想","技能檢視、能力樹、階段清單，以及連結實作或職涯目標的視覺化方式。",["只看見完成的章節","不知道能力是否提升","不清楚離目標還有多遠"],["技能檢視與階段清單","能力樹與成長回饋","連結實作與職涯目標"]],["代表情境 C","時間限制與職涯方向","研究阻力","在職學生的學習時間不固定；部分學生也不確定適合的職涯方向。","服務構想","彈性課程、章節摘要、職涯方向分析、Mentor 支持，以及依學習習慣調整的建議。",["工作與學習時間衝突","難以維持固定進度","不確定適合的職涯方向"],["彈性節奏與章節摘要","依習慣調整學習建議","職涯分析與 Mentor 支持"]]],note:"工作坊以急迫性與發生頻率協助排序；作品集從中挑選三組代表情境呈現，不代表團隊當時只產出這三個方案。",leftLabel:"研究阻力",rightLabel:"服務回應"},
      outcome:{marker:"研究產出與目前狀態",title:"研究完成了哪些產出，服務構想走到哪一步？",body:"這個專案完成了問題定義、關係洞察與服務方向，並把抽象的「關係不夠深」轉成後續可以排序與驗證的機會。以下分開呈現已完成的研究、已形成的服務構想，以及仍需驗證的產品成效。",groups:[["研究產出｜已完成",["9 位學生訪談","3 種人物誌","關係促進與破壞因素","5 個改善切入點"]],["服務構想｜已形成",["Kelly 8／Tom 9 個方向","提問與同儕支持","技能檢視與學習引導","彈性學習與職涯支持"]],["產品成效｜尚待驗證",["方案優先順序與可行性","原型易用性與需求驗證","正式採用與上線狀態","留存與商業成效"]]],closing:"這個階段的價值，是讓團隊不再只談「如何增加黏著」，而是能針對信任、學習引導、社群參與、時間限制與職涯期待，討論具體的服務機會與下一步驗證。"}
    },
    en: {
      pageTitle:"AlphaCamp | Turning learner relationships into service opportunities", eyebrow:"CASE STUDY · USER RESEARCH · SERVICE DESIGN · 2021",
      hero:{title:"From weak post-course engagement\nto five actionable relationship opportunities",deck:"AlphaCamp saw learner interaction with the platform and community decline after course completion. Through student interviews, relationship research, and participatory workshops, the research team translated trust, learning support, and community participation into service opportunities for different learning contexts.",meta:[["Role","UX Researcher | Research team member"],["Team","Timothy, Ricky, Kim, Evy"],["Period","Nov 2020–Jan 2021"],["Scope","Research and workshop planning, interviews, personas, relationship analysis, service ideation"],["Evidence status","Research and service concepts; no claims of launch impact"]],visualCaption:"Conceptual research visual",visualAlt:"Conceptual view of coding education, community support, and career direction"},
      summary:[["Problem","Weak post-course interaction, community participation, and sharing"],["Research","9 student interviews + relationship research"],["Synthesis","5 relationship-improvement opportunities"],["Ideation","8 directions for Kelly / 9 for Tom"]],toc:[["01","Business problem","problem"],["02","Research insights","research"],["03","Synthesis","synthesis"],["04","Service ideation","ideation"],["05","Outputs and status","outcome"]],
      overview:{label:"CASE SUMMARY",title:"Turning “the learner–platform relationship” into a researchable design problem",body:"The team started with weak post-course engagement, identified the factors shaping the relationship, created three personas, synthesized five opportunity areas, and translated the findings into service concepts for different learning situations.",contributionLabel:"MY CONTRIBUTION",contributionIntro:"I was one member of a four-person research team. The roles below distinguish my lead responsibilities from collaborative research outputs.",contributions:[["Lead","Research planning","Structured the research framework, research flow, and internal and participatory workshop approach."],["Collaborative execution","Interviews and synthesis","Participated in student, teaching-assistant, and expert interviews; synthesized records into personas and relationship factors."],["Facilitation lead","Service ideation workshop","Facilitated ideation for Kelly and Tom and organized scenarios by urgency and frequency."],["Design translation","Flows and concept sketches","Translated learning needs into service flows and interface concepts, including a skill tree and question-support interface."]]},
      problem:{marker:"Business problem and research goal",title:"Why did learners rarely stay engaged with the platform after finishing a course?",body:["AlphaCamp observed three recurring signals: interaction declined after course completion, community participation was weaker than expected, and learners rarely shared their achievements without prompting. The team knew the relationship was not continuing, but not where it was breaking down.","Rather than jumping to new features, the study returned to the full learning journey to understand how trust forms, which experiences strengthen or damage the relationship, and what would make learners more willing to participate and share."],note:"Here, “relationship” means continued interaction, trust, learning support, community participation, and willingness to share during and after a course—not abstract brand affinity.",cards:[["01","Stakeholders","Mapped interactions among learners, teaching assistants, experts, and the platform."],["02","Course journey","Located learning stages and touchpoints that might shape the relationship."],["03","Early hypotheses","Turned proto-persona assumptions into questions for interviews."]]},
      research:{marker:"User research and relationship insights",title:"Different learners faced different barriers, and different factors shaped the relationship",body:"The team interviewed nine people learning to code: four AlphaCamp learners and five non-AlphaCamp learners. We also incorporated teaching-assistant and expert perspectives. Topics included motivation, ability anxiety, teaching-assistant influence, emotional support, community value, and brand positioning.",personas:[["KELLY","Career changer","Needed to understand the gap between her skills and industry expectations, plus direction and encouragement through uncertainty.","persona-kelly-mosaic.png"],["TOM","Working upskiller","Needed to balance work and learning, with strong content, efficient use of time, flexible pacing, and habit support.","persona-tom-mosaic.png"],["AMY","Explorer","Valued peer exchange and shared learning; studying alone or lacking similar-level peers reduced participation.","persona-amy-mosaic.png"]],spectrumLabel:"RELATIONSHIP SPECTRUM",spectrumTitle:"The relationship was not binary; it could move from transaction toward understanding and support",spectrum:[["01","One-way transaction","Payment in exchange for content or service; interaction stays functional."],["02","Mutual partnership","Both sides provide value and ongoing cooperation begins."],["03","Two-way exchange","Learners share experiences and expect to be understood and answered."],["04","Deep support","The service understands personal goals and supports difficulty and growth."]],letterLabel:"METHOD | LOVE LETTER & BREAKUP LETTER",letterTitle:"We asked what deepened the relationship—and what made learners want to leave",letterIntro:"The team synthesized participant input into two groups of relationship signals. The image is an anonymous visual reconstruction, not original handwriting.",letterAlt:"Anonymous visual summary of Love Letter and Breakup Letter research",letterGroups:[["LOVE LETTER","Safety, guidance, and growth support","Timely answers, clearer progress, and links between learning content and personal goals strengthened the relationship."],["BREAKUP LETTER","Pressure, isolation, and disconnection","Unsustainable workload, limited real-time interaction, and unclear progress weakened it."]],letterCaption:"The research content was anonymized and visually reconstructed; names, photos, handwriting, and verbatim sentences were not retained.",note:"Isolation was one relationship barrier—not a single, proven cause of churn."},
      synthesis:{marker:"Research synthesis",title:"Turning an abstract relationship into five actionable opportunity areas",body:"The team organized the scattered relationship factors into five opportunities so later workshops could start from a shared problem space. These are opportunity areas, not five launched services.",cards:[["01","First brand impression","Clarify the value of the content, service model, and platform position."],["02","Teaching-assistant quality","Improve response quality, depth, and trust."],["03","Community interaction","Create meaningful exchange and peer support."],["04","Personal growth","Make progress, skill gaps, and next steps visible."],["05","Industry mindset","Connect learning to practice, careers, and industry resources."]]},
      ideation:{marker:"Service ideation and scenario integration",title:"Developing service concepts for different learning situations",body:"The team expanded the five opportunity areas around different learning needs: eight directions for Kelly and nine for Tom. We then organized scenarios by urgency and frequency to identify topics for deeper discussion. These were workshop explorations—not 17 committed or launched features.",directions:[["Kelly | 8 directions","Learning clinic, learning roadmap, Q&A, practice room, side project, career lens, cheer squad, and rest period."],["Tom | 9 directions","Micro-learning, habit support, Q&A, beginner village, learning compass, personalized learning, information library, industry station, and peer learning."]],proof:[["Research input","Learner barriers and relationship factors","Interviews surfaced learning anxiety, time limits, support needs, and career expectations."],["Synthesis","Five opportunity areas","Scattered insights became a shared problem space for ideation."],["Service output","8 directions for Kelly / 9 for Tom","Concepts responded to learning situations rather than defining a feature backlog."]],scenarios:[["SCENARIO A","Blocked on an assignment and afraid to ask","Research barrier","Learners struggled to describe a problem, find someone to ask, post publicly, or judge whether online answers were reliable.","Service concept","Practice describing questions, anonymous asking, peer grouping by level, and teaching-assistant or coach support.",["Cannot describe the problem","Afraid to ask publicly","Cannot judge answer quality"],["Question-framing practice","Anonymous asking and level groups","Trusted TA or coach support"]],["SCENARIO B","Unsure what was actually learned","Research barrier","Learners remained unsure about their ability, progress, and distance from a target role.","Service concept","Skill reviews, a capability tree, stage checklists, and visuals linked to practice or career goals.",["Only sees completed chapters","Cannot tell whether skills improved","Unclear distance to the goal"],["Skill review and stage checklist","Capability tree and growth feedback","Links to practice and career goals"]],["SCENARIO C","Time constraints and career direction","Research barrier","Working learners had inconsistent study time, while some learners were unsure which career path suited them.","Service concept","Flexible pacing, chapter summaries, career-path analysis, mentor support, and suggestions adapted to learning habits.",["Work and learning conflict","Hard to maintain pace","Unclear career direction"],["Flexible pacing and summaries","Habit-based recommendations","Career analysis and mentor support"]]],note:"Urgency and frequency helped prioritize workshop discussion. The portfolio shows three representative scenarios—not the full set of team outputs.",leftLabel:"Research barrier",rightLabel:"Service response"},
      outcome:{marker:"Research outputs and current status",title:"What did the research produce, and how far did the service concepts progress?",body:"The project completed problem definition, relationship insights, and service directions. It turned a vague concern—“the relationship is not deep enough”—into opportunities that could be prioritized and tested next.",groups:[["Research outputs | Complete",["9 student interviews","3 personas","Relationship-strengthening and damaging factors","5 opportunity areas"]],["Service concepts | Formed",["8 Kelly / 9 Tom directions","Question and peer support","Skill review and learning guidance","Flexible learning and career support"]],["Product impact | Not yet validated",["Priority and feasibility","Prototype usability and needs validation","Formal adoption and launch status","Retention and business impact"]]],closing:"The value at this stage was moving the team beyond “how do we increase stickiness?” toward concrete discussions about trust, learning guidance, community participation, time constraints, career expectations, and what to validate next."}
    },
    ja: {
      pageTitle:"AlphaCamp｜学習者との関係をサービス機会へ変換",eyebrow:"ケーススタディ · ユーザーリサーチ · サービスデザイン · 2021",
      hero:{title:"受講後の接点減少から、\n関係改善の5つの切り口を見つける",deck:"AlphaCampでは、受講修了後に学習者とプラットフォーム／コミュニティの接点が徐々に減っていました。学生インタビュー、関係性リサーチ、参加型ワークショップを通じて、信頼・学習支援・コミュニティ参加に影響する要因を、学習状況ごとのサービス改善機会へ変換しました。",meta:[["役割","UXリサーチャー｜リサーチチームメンバー"],["チーム","Timothy、Ricky、Kim、Evy"],["期間","2020.11–2021.01"],["担当範囲","リサーチ／ワークショップ設計、インタビュー、ペルソナ、関係性分析、サービス発想"],["エビデンスの範囲","リサーチとサービス構想。リリース後の成果は主張しない"]],visualCaption:"リサーチ状況のコンセプトビジュアル",visualAlt:"プログラミング学習、コミュニティ支援、キャリア方向を表すコンセプトビジュアル"},
      summary:[["課題","受講後の接点、コミュニティ参加、発信が不足"],["調査","学生9名へのインタビュー＋関係性リサーチ"],["収束","関係改善の5つの切り口"],["発想","Kelly 8案／Tom 9案"]],toc:[["01","事業課題","problem"],["02","調査インサイト","research"],["03","調査の収束","synthesis"],["04","サービス発想","ideation"],["05","成果物と現状","outcome"]],
      overview:{label:"ケース概要",title:"「学生とプラットフォームの関係」を、調査可能なデザイン課題へ分解",body:"チームは受講後の接点減少を起点に、関係へ影響する要因を特定し、3つのペルソナと5つの改善機会を整理。さらに学習状況ごとのサービス構想へ展開しました。",contributionLabel:"担当したこと",contributionIntro:"4名のリサーチチームの一員として参加しました。以下では、私がリードした範囲とチームで共同実施した範囲を分けて示します。",contributions:[["リード","リサーチ設計","リサーチの枠組みと進行、社内／参加型ワークショップの進め方を設計。"],["共同実施","インタビューと統合","学生・TA・専門家インタビューに参加し、記録をペルソナと関係要因へ整理。"],["進行をリード","サービス発想ワークショップ","KellyとTomのサービス案創出を進行し、緊急度と発生頻度で状況を整理。"],["デザインへの変換","フローと構想スケッチ","学習ニーズをサービスフローと、スキルツリーや質問支援画面などの構想へ変換。"]]},
      problem:{marker:"事業課題と調査目的",title:"なぜ受講修了後、学習者はプラットフォームとの接点を持ち続けないのか？",body:["AlphaCampでは、受講修了後の接点減少、想定を下回るコミュニティ参加、自発的な学習成果の発信不足という3つの兆候がありました。しかし、学習体験のどこで関係が途切れているかは明確ではありませんでした。","そこで新機能を先に考えるのではなく、学習体験全体へ戻り、信頼が生まれる条件、関係を強める／弱める体験、継続参加や発信につながる条件を調べました。"],note:"ここでいう「関係」とは、受講中／受講後の継続的な接点、信頼、学習支援、コミュニティ参加、自発的な発信を指し、抽象的なブランド好意だけではありません。",cards:[["01","ステークホルダー","学生、TA、専門家、プラットフォーム間の接点を整理。"],["02","学習ジャーニー","関係へ影響しうる学習段階とタッチポイントを特定。"],["03","初期仮説","仮説ペルソナをインタビューで確認すべき問いへ変換。"]]},
      research:{marker:"ユーザーリサーチと関係性インサイト",title:"学習者ごとに異なる壁があり、関係へ影響する要因も異なっていた",body:"プログラミングを学ぶ学生9名（AlphaCamp受講者4名、非受講者5名）へインタビューし、TAと専門家の視点も整理しました。学習動機、スキルへの不安、TAの影響、感情面の支援、コミュニティ価値、ブランド認識などを扱いました。",personas:[["KELLY","転職志向","自分のスキルと業界要件の差を知り、不確実さや挫折のなかで方向づけと励ましを必要としていました。","persona-kelly-mosaic.png"],["TOM","仕事と両立する学習者","仕事と学習を両立しながら、内容品質、時間効率、柔軟な進度、習慣化を重視していました。","persona-tom-mosaic.png"],["AMY","探索型学習者","仲間との交流と共同学習を重視し、一人きりの学習や同程度の仲間不足が参加を妨げていました。","persona-amy-mosaic.png"]],spectrumLabel:"関係性のスペクトラム",spectrumTitle:"関係は有無ではなく、取引から理解と支援へ段階的に深まる",spectrum:[["01","一方向の取引","支払いと引き換えに内容やサービスを得る、機能中心の接点。"],["02","相互利益のパートナー","双方が価値を提供し、継続的な協力が始まる。"],["03","双方向の交流","経験を共有し、理解と反応を期待する。"],["04","深い支援","個人目標を理解し、困難と成長の両方を支える。"]],letterLabel:"調査手法｜Love Letter / Breakup Letter",letterTitle:"関係を深めるものと、離れたくなる要因を言語化してもらう",letterIntro:"参加者の内容を、関係を強める／弱める2群のシグナルへ整理しました。下図は匿名化した再構成で、原本の手書き資料ではありません。",letterAlt:"Love LetterとBreakup Letterの匿名化ビジュアル要約",letterGroups:[["LOVE LETTER","安心感、ガイド、成長支援","適切な回答、進捗理解、学習内容と個人目標の接続が関係を強めました。"],["BREAKUP LETTER","負荷、孤立、接点の断絶","維持しづらい学習負荷、即時的な交流不足、現在地の不明確さが関係を弱めました。"]],letterCaption:"調査内容を匿名化して再構成。参加者名、写真、筆跡、原文は保持していません。",note:"孤立感は関係を弱める一要因であり、離脱の単一原因として実証したものではありません。"},
      synthesis:{marker:"調査の収束",title:"抽象的な関係性を、改善可能な5つの機会へ変換",body:"分散していた関係要因を5つの改善機会へ整理し、後続ワークショップが共通の問題空間から始められるようにしました。これは5つのリリース済みサービスではありません。",cards:[["01","ブランドの第一印象","内容価値、提供方法、プラットフォームの立ち位置を明確化。"],["02","TAの品質","回答の質、深さ、信頼を高める。"],["03","コミュニティ交流","実感のある交流と仲間の支援をつくる。"],["04","個人の成長","進捗、スキル差、次の一歩を可視化。"],["05","業界視点","実務、キャリア、業界資源と学習を接続。"]]},
      ideation:{marker:"サービス発想と状況への統合",title:"5つの改善機会から、学習状況ごとのサービス構想へ",body:"異なる学習ニーズを対象に、Kellyでは8案、Tomでは9案へ発想を展開しました。その後、状況の緊急度と発生頻度で整理し、深掘りするテーマを選びました。17機能の開発決定やリリースを意味するものではありません。",directions:[["Kelly｜8つの方向","学習クリニック、学習ロードマップ、Q&A、練習室、Side Project、キャリア可視化、応援、休息。"],["Tom｜9つの方向","マイクロラーニング、習慣支援、Q&A、初心者コミュニティ、学習コンパス、個別学習、情報ライブラリ、業界情報、共同学習。"]],proof:[["調査入力","学習上の壁と関係要因","学習不安、時間制約、支援ニーズ、キャリア期待を把握。"],["収束方法","5つの改善機会","分散したインサイトを共通の問題空間へ整理。"],["サービス出力","Kelly 8案／Tom 9案","機能リストではなく、学習状況に応じた構想として展開。"]],scenarios:[["代表状況 A","課題で詰まり、質問できない","調査で見えた壁","問題を説明できない、質問相手がいない、公開投稿が怖い、回答の信頼性を判断できない。","サービス構想","質問の言語化練習、匿名質問、習熟度別グループ、TA／コーチの支援。",["問題を説明できない","公開質問が怖い","回答の質を判断できない"],["質問整理の練習","匿名質問と習熟度別グループ","信頼できるTA／コーチ"]],["代表状況 B","何を身につけたか分からない","調査で見えた壁","自分の能力、進捗、目標職種までの距離が分からない。","サービス構想","スキル確認、能力ツリー、段階チェックリスト、実践／キャリア目標との接続。",["完了章しか見えない","能力向上を実感できない","目標までの距離が不明"],["スキル確認と段階リスト","能力ツリーと成長フィードバック","実践とキャリア目標へ接続"]],["代表状況 C","時間制約とキャリア方向","調査で見えた壁","仕事を持つ学習者は時間が不規則で、適したキャリア方向が分からない人もいました。","サービス構想","柔軟な進度、章ごとの要約、キャリア分析、メンター支援、習慣に応じた提案。",["仕事と学習が衝突","一定の進度を保てない","キャリア方向が不明"],["柔軟な進度と要約","習慣に合わせた提案","キャリア分析とメンター支援"]]],note:"ワークショップでは緊急度と発生頻度で優先度を整理しました。作品集では代表的な3状況のみを掲載しており、チームの全成果を意味しません。",leftLabel:"調査で見えた壁",rightLabel:"サービスの応答"},
      outcome:{marker:"調査成果物と現在地",title:"調査で何を完成し、サービス構想はどこまで進んだか？",body:"問題定義、関係性インサイト、サービス方向までを完成し、「関係が浅い」という抽象的な課題を、優先順位づけと検証が可能な機会へ変換しました。",groups:[["調査成果物｜完了",["学生9名へのインタビュー","3つのペルソナ","関係を強める／弱める要因","5つの改善機会"]],["サービス構想｜形成",["Kelly 8案／Tom 9案","質問と仲間の支援","スキル確認と学習ガイド","柔軟な学習とキャリア支援"]],["プロダクト成果｜未検証",["優先順位と実現可能性","プロトタイプのユーザビリティとニーズ検証","正式採用／リリース状況","継続率と事業成果"]]],closing:"この段階の価値は、「どう粘着性を上げるか」だけでなく、信頼、学習ガイド、コミュニティ参加、時間制約、キャリア期待を具体的なサービス機会と次の検証課題として議論できる状態をつくったことです。"}
    }
  };

  const escapeHtml = value => String(value ?? "").replace(/[&<>'"]/g, ch => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[ch]);
  const titleLines = value => value.split("\n").map(line => `<span>${escapeHtml(line)}</span>`).join("<br>");
  const cards = (items, className="") => `<div class="alpha-card-grid ${className}">${items.map(item => `<article class="alpha-card"><b>${escapeHtml(item[0])}</b><h3>${escapeHtml(item[1])}</h3><p>${escapeHtml(item[2])}</p></article>`).join("")}</div>`;
  const render = ({locale, project, ui, tail=""}) => {
    const c = CASES[locale] || CASES.en;
    return `<div class="case-page case-page--alphacamp-approved" data-page="case" data-project="alphacamp" id="case-content" style="--project-accent:${escapeHtml(project.accent)};--project-soft:${escapeHtml(project.soft)};--project-dark:${escapeHtml(project.dark)}">
      <section class="alpha-hero"><div class="alpha-shell"><a class="case-back text-link" href="#home" data-home-target="work">← ${escapeHtml(ui.backToWork)}</a><div class="alpha-hero__frame"><div class="alpha-hero__copy"><span class="alpha-eyebrow">${escapeHtml(c.eyebrow)}</span><h1>${titleLines(c.hero.title)}</h1><p class="alpha-hero__lead">${escapeHtml(c.hero.deck)}</p><div class="alpha-meta">${c.hero.meta.map((item,index)=>`<div class="${index===4?'alpha-meta__wide':''}"><span>${escapeHtml(item[0])}</span><strong>${escapeHtml(item[1])}</strong></div>`).join("")}</div></div><figure class="alpha-hero__visual"><img src="assets/AlphaCamp/alphacamp-hero-v2.png" alt="${escapeHtml(c.hero.visualAlt)}"><figcaption>${escapeHtml(c.hero.visualCaption)}</figcaption></figure></div></div></section>
      <section class="alpha-summary"><div class="alpha-shell alpha-summary__grid">${c.summary.map(item=>`<article><span>${escapeHtml(item[0])}</span><strong>${escapeHtml(item[1])}</strong></article>`).join("")}</div></section>
      <nav class="alpha-index" aria-label="${escapeHtml(c.overview.label)}">${c.toc.map(item=>`<a href="#${item[2]}" data-alpha-section="${item[2]}">${escapeHtml(item[0])} ${escapeHtml(item[1])}</a>`).join("")}</nav>
      <section class="alpha-section" id="overview"><div class="alpha-shell alpha-section__grid"><aside class="alpha-marker"><strong>00</strong><span>${escapeHtml(c.overview.label)}</span></aside><div class="alpha-content"><h2>${escapeHtml(c.overview.title)}</h2><p class="alpha-deck">${escapeHtml(c.overview.body)}</p><section class="alpha-contribution"><div class="alpha-contribution__intro"><h3>${escapeHtml(c.overview.contributionLabel)}</h3><p>${escapeHtml(c.overview.contributionIntro)}</p></div><div class="alpha-contribution__grid">${c.overview.contributions.map(item=>`<article><span>${escapeHtml(item[0])}</span><h4>${escapeHtml(item[1])}</h4><p>${escapeHtml(item[2])}</p></article>`).join("")}</div></section></div></div></section>
      <section class="alpha-section" id="problem"><div class="alpha-shell alpha-section__grid"><aside class="alpha-marker"><strong>01</strong><span>${escapeHtml(c.problem.marker)}</span></aside><div class="alpha-content"><h2>${escapeHtml(c.problem.title)}</h2>${c.problem.body.map(p=>`<p class="alpha-deck">${escapeHtml(p)}</p>`).join("")}<div class="alpha-note">${escapeHtml(c.problem.note)}</div>${cards(c.problem.cards,"alpha-card-grid--3")}</div></div></section>
      <section class="alpha-section" id="research"><div class="alpha-shell alpha-section__grid"><aside class="alpha-marker"><strong>02</strong><span>${escapeHtml(c.research.marker)}</span></aside><div class="alpha-content"><h2>${escapeHtml(c.research.title)}</h2><p class="alpha-deck">${escapeHtml(c.research.body)}</p><div class="alpha-card-grid alpha-card-grid--3">${c.research.personas.map(item=>`<article class="alpha-card alpha-persona-card"><img src="assets/AlphaCamp/${escapeHtml(item[3])}" alt="${escapeHtml(`${item[0]} persona; participant photo pixelated`)}"><b>${escapeHtml(item[0])}</b><h3>${escapeHtml(item[1])}</h3><p>${escapeHtml(item[2])}</p></article>`).join("")}</div><div class="alpha-native-visual"><span class="alpha-native-visual__label">${escapeHtml(c.research.spectrumLabel)}</span><h3>${escapeHtml(c.research.spectrumTitle)}</h3><div class="alpha-spectrum">${c.research.spectrum.map(item=>`<article><span>${escapeHtml(item[0])}</span><strong>${escapeHtml(item[1])}</strong><p>${escapeHtml(item[2])}</p></article>`).join("")}</div></div><figure class="alpha-letter-study"><div class="alpha-letter-study__intro"><span class="alpha-native-visual__label">${escapeHtml(c.research.letterLabel)}</span><h3>${escapeHtml(c.research.letterTitle)}</h3><p>${escapeHtml(c.research.letterIntro)}</p></div><div class="alpha-letter-study__frame" data-zoom-src="assets/AlphaCamp/alphacamp-letters-summary-v1.png" data-zoom-caption="${escapeHtml(c.research.letterCaption)}" tabindex="0" role="button" aria-label="${escapeHtml(ui.openImage)}"><img src="assets/AlphaCamp/alphacamp-letters-summary-v1.png" alt="${escapeHtml(c.research.letterAlt)}"></div><div class="alpha-letter-study__legend">${c.research.letterGroups.map(item=>`<article><span>${escapeHtml(item[0])}</span><h4>${escapeHtml(item[1])}</h4><p>${escapeHtml(item[2])}</p></article>`).join("")}</div><figcaption>${escapeHtml(c.research.letterCaption)}</figcaption></figure><div class="alpha-note">${escapeHtml(c.research.note)}</div></div></div></section>
      <section class="alpha-section" id="synthesis"><div class="alpha-shell alpha-section__grid"><aside class="alpha-marker"><strong>03</strong><span>${escapeHtml(c.synthesis.marker)}</span></aside><div class="alpha-content"><h2>${escapeHtml(c.synthesis.title)}</h2><p class="alpha-deck">${escapeHtml(c.synthesis.body)}</p>${cards(c.synthesis.cards,"alpha-card-grid--5")}</div></div></section>
      <section class="alpha-section" id="ideation"><div class="alpha-shell alpha-section__grid"><aside class="alpha-marker"><strong>04</strong><span>${escapeHtml(c.ideation.marker)}</span></aside><div class="alpha-content"><h2>${escapeHtml(c.ideation.title)}</h2><p class="alpha-deck">${escapeHtml(c.ideation.body)}</p><div class="alpha-direction-grid">${c.ideation.directions.map(item=>`<article><h3>${escapeHtml(item[0])}</h3><p>${escapeHtml(item[1])}</p></article>`).join("")}</div><div class="alpha-proof-strip">${c.ideation.proof.map(item=>`<article><span>${escapeHtml(item[0])}</span><strong>${escapeHtml(item[1])}</strong><p>${escapeHtml(item[2])}</p></article>`).join("")}</div>${c.ideation.scenarios.map(s=>`<article class="alpha-scenario"><div><span class="alpha-eyebrow">${escapeHtml(s[0])}</span><h3>${escapeHtml(s[1])}</h3><h4>${escapeHtml(s[2])}</h4><p>${escapeHtml(s[3])}</p><h4>${escapeHtml(s[4])}</h4><p>${escapeHtml(s[5])}</p></div><div class="alpha-scenario-visual"><div class="alpha-scenario-visual__side"><span>${escapeHtml(c.ideation.leftLabel)}</span>${s[6].map(x=>`<div class="alpha-scenario-visual__item">${escapeHtml(x)}</div>`).join("")}</div><div class="alpha-scenario-visual__arrow">→</div><div class="alpha-scenario-visual__side alpha-scenario-visual__side--answer"><span>${escapeHtml(c.ideation.rightLabel)}</span>${s[7].map(x=>`<div class="alpha-scenario-visual__item">${escapeHtml(x)}</div>`).join("")}</div></div></article>`).join("")}<div class="alpha-note">${escapeHtml(c.ideation.note)}</div></div></div></section>
      <section class="alpha-section" id="outcome"><div class="alpha-shell alpha-section__grid"><aside class="alpha-marker"><strong>05</strong><span>${escapeHtml(c.outcome.marker)}</span></aside><div class="alpha-content"><h2>${escapeHtml(c.outcome.title)}</h2><p class="alpha-deck">${escapeHtml(c.outcome.body)}</p><div class="alpha-status">${c.outcome.groups.map(item=>`<article><h3>${escapeHtml(item[0])}</h3><ul>${item[1].map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul></article>`).join("")}</div><div class="alpha-conclusion"><p>${escapeHtml(c.outcome.closing)}</p></div></div></div></section>${tail}</div>`;
  };

  let cleanup = null;
  const destroy = () => { cleanup?.(); cleanup = null; };
  const setup = () => {
    destroy();
    const nav = document.querySelector(".case-page--alphacamp-approved .alpha-index");
    const links = [...document.querySelectorAll(".case-page--alphacamp-approved [data-alpha-section]")];
    const sections = links.map(link => document.getElementById(link.dataset.alphaSection)).filter(Boolean);
    let frame = 0;
    const update = () => { frame = 0; if (!nav || !sections.length) return; const line = Math.max(150,innerHeight*.3); nav.classList.toggle("is-visible",sections[0].getBoundingClientRect().top<=line&&sections.at(-1).getBoundingClientRect().bottom>100); let active=sections[0]; sections.forEach(section=>{if(section.getBoundingClientRect().top<=line)active=section}); links.forEach(link=>link.classList.toggle("is-active",link.dataset.alphaSection===active.id)); };
    const schedule = () => { if (!frame) frame=requestAnimationFrame(update); };
    addEventListener("scroll",schedule,{passive:true}); addEventListener("resize",schedule); update();
    cleanup=()=>{removeEventListener("scroll",schedule);removeEventListener("resize",schedule);if(frame)cancelAnimationFrame(frame)};
  };
  window.ALPHACAMP_CASE_PAGE={getContent:locale=>CASES[locale]||CASES.en,render,setup,destroy};
})();
